### ISSUE TITLE
sin, tan, and log1p do not return correct sign for -0.0 

### ISSUE THREAD

**Issue by musm** [shibatch/sleef#1]
Both sin and sin_u1,  tan and tan_u1 , log1p do not return correct sign for -0.0, noticed  this during testing.  Thanks.
Fix for sin and sin_u1 is simple , just needs a flipsign operation

**Comment by musm** [comment]
See https://github.com/musm/Libm.jl/blob/master/src/Sleef/log.jl#L44  for the fix for `log1p`

**Comment by shibatch** [comment]
This should be now fixed in 2.90.
Test cases for negative zeroes are added.
