### ISSUE TITLE
renamesse2.h not generated correctly on Darwin

### ISSUE THREAD

**Issue by cnweaver** [shibatch/sleef#102]
The command to generate this file is currently

	$(FLOCK) mkrename.lock ./mkrename 2 4 sse2 > renamesse2.h

which omits both the `-c` flag and correct quoting, leading to a failure when noflock.sh attempts to execute `2`. 

	$(FLOCK) mkrename.lock -c './mkrename 2 4 sse2 > renamesse2.h'

works as intended. I have not tested whether the existing version works on Linux, but based on reading the `flock` manpage it does not appear that it should, since `-c` is apparently required for a command to be executed.

**Comment by shibatch** [comment]
We are migrating the build system to cmake.
There will be no problems of this kind in the next release.

**Comment by fpetrogalli-arm** [comment]
The build system of SLEEF has migrated to cmake with #104 and #112, we can safely close this issue.

@cnweaver, please verify that the new cmake build system works for you.
