### ISSUE TITLE
On EPYC/gcc 4.8, testers not linked with common.a

### ISSUE THREAD

**Issue by pmucci** [shibatch/sleef#120]
Hi all,

Just testing out this library on a new AMD EPYC. Using the latest git repo, cmake3 and gcc 4.8, the library builds but the tests fail when trying to link the tester because of undefined reference to Sleef_x86CpuID. Looking into link.txt into tester.dir shows the reason why. The shared library is linked after the libcommon.a meaning the dependencies of that shared library won't be satisfied. 

I don't know Cmake or I'd submit a patch, but the solution for me was to add the ../common/libcommon.a to the end of src/libm-tester/CMakeFiles/tester.dir/link.txt

This is against current git head. I must assume that others are seeing this? I couldn't find anything special about my config that would cause that ordering.

The tests appear to pass ok, but alas, I cannot use it because libsleef.so does not include common.a as well. I need to keep looking.

**Comment by pmucci** [comment]
Ok, my error was CMAKE_BUILD_TYPE set to an invalid string. Trying it again with that set to RelWithDebInfo seems to have worked. I'd say this isn't a bug per-se, but might want to check that string.

**Comment by shibatch** [comment]
Hi Philip,

For some reasons, the functions in common.c are now included in libsleefdft. I will move them to libsleef.

**Comment by pmucci** [comment]
Thanks. Is there a way to generate libm bindings?

Philip J. Mucci
Minimal Metrics LLC
+1 415.841.3577 (global)
+46 72.172.2581 (direct)
phil@minimalmetrics.com <mailto:phil@minimalmetrics.com>

**Comment by shibatch** [comment]
I will fix this problem in the next week. Please be patient. 🙂
