### ISSUE TITLE
No dispatcher functions being build

### ISSUE THREAD

**Issue by mkbosmans** [shibatch/sleef#121]
On Linux x86 and building with CMake, there are no generic functions in the resulting library.

For example, I do see Sleef_sind4_u10avx, Sleef_sind4_u10avx2 and Sleef_sind4_u10fma4, but no Sleef_sind4_u10.

The mkdisp executable is build. Am I supposed to do something with it, or should that happen automatically during building the library?

**Comment by shibatch** [comment]
Hi Maarten,

Thank you for reporting. I will fix this problem.
