### ISSUE TITLE
Expose vector ABI names for each of the vector extentions

### ISSUE THREAD

**Issue by fpetrogalli-arm** [shibatch/sleef#13]
We need to expose the vector routines using the name mangling functions defined in the target vector ABI.

For Intel vector extensions, the mangling function can be found at [1]. The vector ABI for AArch64 is not public yet, but it is exposed in this patch [2] for clang.

For our math functions (they are all non-masked), the name mangling functions reduces to:

    _ZGV<isa>N<vlen><vparameters>_<original_name>

For example, a `cos` function will become:

    _ZGVnN2v_cos  // AArch64 AdvSIMD, see [2], <isa> == n
    _ZGVdN4v_cos  // Intel AVX2
    _ZGVeN8v_cos  // Intel AVX512

Another example, for `powf`:

    _ZGVnN4vv_powf  // AArch64 AdvSIMD, see [2], <isa> == n, two vector input parameters (vv)
    _ZGVdN8vv_powf  // Intel AVX2
    _ZGVeN16vv_powf  // Intel AVX512
    
The reason for adding these symbols is that it will allow compiler like `gcc` and `clang` to link the library transparently when vectorizing math routines in loops, as in the example in [3] (we will need to provide a header file with `math.h` definition and expose teh vector math routines by means of `#pragma omp declare simd`).

Note that some of the vector extensions that SLEEF supports are not specified in the vector ABI in [1] (e.g. SSE2). We can skip to create vector ABI symbols for such vector extensions for now.

[1] https://sourceware.org/glibc/wiki/libmvec?action=AttachFile&do=view&target=VectorABI.txt
[2] https://reviews.llvm.org/D30739
[3] https://godbolt.org/g/DnxT6D

**Comment by shibatch** [comment]
These name are not human-friendly.
llvm is also calling SLEEF functions with other names.

https://reviews.llvm.org/D24951

I think we need to do something to alleviate this situation.
Do you think it is a good idea to expose the functions under the mangled names, and rename them to human-friendly names in the header file using many #define?

**Comment by shibatch** [comment]
I am also considering about SVML-compatibility mode, which allows the users to call SLEEF functions with SVML's function names.

**Comment by fpetrogalli-arm** [comment]
Exposing the function under the vector ABI mangled names is very important. By doing so, we will be able to interface the library with any compiler that know how to vectorize the routines in`math.h`. I agree they might not be human-friendly, but they are compiler-friendly.

Agree, we can expose any  other human-friendly name using `#define`s in the header file.

**Comment by hfinkel** [comment]
I'd rather we not use preprocessor macros for this in public headers. That's C++ unfriendly ;) -- Better would be:
 1. wrapping inline functions in the header file
 2. aliases (e.g. void bar(void) __attribute__((alias("foo")));)

I don't have a strong preference, but lean toward using aliases.

**Comment by fpetrogalli-arm** [comment]
Right, `#define` will make C++ unhappy. The `alias` attribute works perfectly:
```
$ cat lib.h
#ifndef LIB_H
#define LIB_H

double VABI_cos(double);

double xcos(double) __attribute__ ((alias("VABI_cos")));
double LLVM_cos(double)  __attribute__ ((alias("VABI_cos")));
double SLEEF_cos(double) __attribute__ ((alias("VABI_cos")));

#endif

$ cat lib.c
#include "lib.h"

extern double z;

double VABI_cos(double x) {
  return x*x + x*x*x + z;
  }
$ gcc -c lib.c -O3 -g
$ nm -l lib.o
0000000000000000 T LLVM_cos	lib.c:6
0000000000000000 T SLEEF_cos	lib.c:6
0000000000000000 T VABI_cos	lib.c:5
0000000000000000 T xcos	lib.c:6
                 U z	lib.c:6
```

**Comment by fpetrogalli-arm** [comment]
@shibatch here is a summary of the names that should be associated to the functions.

```
_ZGV<isa>N<vlen><vparameters>_<original_name>

<isa> = 'b'    // SSE
          | 'c'  // AVX
          | 'd'  // AVX2
          | 'e'  // AVX512
          | 'n' // AArch64 Advanced SIMD
```

`<vlen>` is the number of lanes provided by the underlying `vdouble`/`vfloat`, and of course it depends on the `typedef` in the helper files.

`<vparameters>` is either `v` for single input function, or `vv` for functions with two input parameters. 

`original_name` is the C name of the correspondent math function in `math.h`, e.g. `cos` for `xcos` and `atanf` for `xatanf`.

I think this information should be enough to make you generate all the names for the ISAs I have listed.

It would be good to have also tests that use `nm` to check that the aliases are available in `libsleef.so`.

**Comment by shibatch** [comment]
There are functions that return a double2 value like  Sleef_sincosd2_u10sse2.
Is it okay to change the specifications of these functions so that they have the same function prototypes as the equivalent functions in SVML?

**Comment by shibatch** [comment]
glibc's specification is different from SVML.

void sincos(double x, double *sin, double *cos);

SVML is like this.

__m128d _mm_sincos_pd (__m128d * mem_addr, __m128d a);

We need to determine which function prototype to adopt.

**Comment by fpetrogalli-arm** [comment]
Please use the `glibc` prototypes. Later we can add an SVML wrapper. 
The same is done in `glibc`, see

(symbols) https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/x86_64/fpu/svml_d_sincos4_core.S;h=3bcd09b62d84b4b7ce15e0242a4b21b1bf7b21f9;hb=HEAD

and

(compatibility layer SVML/glibc)
https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/x86_64/fpu/svml_s_wrapper_impl.h;h=cd6d58361c03253e38b2b0ff041a00bbbd85796b;hb=HEAD

**Comment by shibatch** [comment]
I was trying to read the source code, but I don't understand why vlen and the stride of l parameters do not match. If my understanding is correct, those sincos functions should have symbols of _ZGVbNXvlYlY_sincos where X == Y.

It seems that there is only one main part of sincosf, which is in s_sincosf.S, and there is no main part of the double precision version of sincos.

**Comment by fpetrogalli-arm** [comment]
The `vl8l8` in `ZGVdN4vl8l8_sincos` if for the three parameters of the `void sincos(double x, double *sin, double *cos);`


* `v` is for `x` -> regular vector
* `l8` is for `sin` and `cos` parameters. It means "linear with step 8", or `linear(sin:8)` in OpenMP syntax. `sin` and `cos` are `double *`, so they increment of 8 bytes. `linear` refers to concurrent invocation of the scalar version, that is why it is the same value for functions processing 2, 4 and 8 values

**Comment by shibatch** [comment]
Is the unit of the l parameter byte? I can't find such description.

**Comment by shibatch** [comment]
Does ZGVdN4vl8l8_sincos executes sincos of length 4 vector twice?

**Comment by fpetrogalli-arm** [comment]
No, `l` doesn't have any unit of measure, it is just a number. It is 8 in this particular case because it refers to concurrent invocation of  `sincos(double , double * , double *)` in a scalar loop.

In the following example the invocations of `sincos` at iterations `i` and `i + 1` will operate on `&sin[i],&cos[i]` and  `&sin[i+1],&cos[i+1]` respectively. The actual step is then `&sin[i+1] - &sin[i]` (same for `cos`), which is 8 because  the underlying scalar type it 8-byte long(`double`).

```
// data types as needed
for (int i=0; i < N; ++i) {
  sincos(x[i], &sin[i], &cos[i]);
} 
```

For `sincosf`, the linear step is 4 as it is referring to pointers whose underlying data type is 4-byte long (`float`). See https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/x86_64/fpu/svml_s_sincosf4_core.S;h=2ab33b59a766e572547710bfc7a928216a8c9474;hb=HEAD

`_ZGVdN4vl8l8_sincos` processes 4 elements at once. I am not sure what you mean by "executes sincos of length 4 vector twice".

**Comment by shibatch** [comment]
I still don't understand. Why the l parameter is 8 when _ZGVdN4vl8l8_sincos processes 4 elements at once? Why isn't it 4?

I tried it with gcc-7.1, but it does not generate a code that calls the vectorized sincos even if I use OpenMP pragma.

**Comment by fpetrogalli-arm** [comment]
The vector functions are classified using the `declare simd` directive of OpenMP, as explained in https://sourceware.org/glibc/wiki/libmvec?action=AttachFile&do=view&target=VectorABI.txt

In particular, line 106 describes the `l` token, which is associated to the `linear` clause of OpenMP.

The `sincos` vector function name has been generated by the following declaration:

```
#pragma omp declare simd linear(sin:8,cos:8)
void sincos (double x, double * sin, double *cos);
```

The value of `8` is correct because it is referring to the stride of `sin` and `cos` values in consecutive invocations of `sincos` (`i` and `i + 1` as in the loop example I have sent you before).

The declaration for the vector version of `sincosf` is:
```
#pragma omp declare simd linear(sin:4,cos:4)
void sincosf (float x, float * sin, float *cos);
```
The following example might help finding out why.
```
#include <stdio.h>
#define N 10
int main(void) {
  double a[N];
  float b[N];
  int i;
  for (i = 0; i < N; ++i) {
    printf("a = %p ", (void *)&a[i]);
    printf("b = %p\n", (void *)&b[i]);
  }
}
```
The output follows, as you can see the `double *` step is 8, while the `float *` step is 4.
```
a = 0x7fff52d02b50 b = 0x7fff52d02b20
a = 0x7fff52d02b58 b = 0x7fff52d02b24
a = 0x7fff52d02b60 b = 0x7fff52d02b28
a = 0x7fff52d02b68 b = 0x7fff52d02b2c
a = 0x7fff52d02b70 b = 0x7fff52d02b30
a = 0x7fff52d02b78 b = 0x7fff52d02b34
a = 0x7fff52d02b80 b = 0x7fff52d02b38
a = 0x7fff52d02b88 b = 0x7fff52d02b3c
a = 0x7fff52d02b90 b = 0x7fff52d02b40
a = 0x7fff52d02b98 b = 0x7fff52d02b44
```

**Comment by shibatch** [comment]
So, the unit of the l parameter is byte, after all. I did some experiments with gcc, and that explains everything.

**Comment by fpetrogalli-arm** [comment]
yes, it is bytes in the case of pointers.

I think you can alternatively think of `linear(var:step)` as a description of the operation `var = var + step` in terms of pragma. I guess it is fair to say that the unit of measure of `step` is the same as the unit of measure of `var`.

**Comment by fpetrogalli-arm** [comment]
Done in #25
