### ISSUE TITLE
[GNUABI] Finite symbols tests

### ISSUE THREAD

**Issue by fpetrogalli-arm** [shibatch/sleef#145]
The test in https://github.com/shibatch/sleef/blob/master/src/libm-tester/finite_names_testing.c make sure that the finite symbols expected for GLIBC compatibility are available in the library.

They are currently checking only a couple of functions for the Intel vector extensions.

We should decide whether we want to keep them and extend them to all the finite symbols and all the supported vector extensions, or if we want to remove them.

Any thoughts?

One argument for keeping them and extending them is the following. I came up with this idea when I first used the library in our compiler. The compiler was generating the finite names (because of the `-ffast-math` option) which were not available in the library. I added them in the library and decided that I should have made a regression tests to prevent the symbols to disappear.

**Comment by shibatch** [comment]
Is just checking if the symbols are exported? If so, testing using nm command would be easier to understand.

In my opinion, checking everything is desirable, but we need to come up with a good way to reduce the time taken by each testing.

If it is better to check if each function works correctly, I think modifying tester3 and checking if the functions return the same values as the non-finite functions is reasonable.

**Comment by fpetrogalli-arm** [comment]
> Is just checking if the symbols are exported? If so, testing using nm command would be easier to understand.

Yes, it is just checking that the finite symbols are available (for a subset of functions). Originally the tests where written for the makefile system, and they were using the `nm` tool to check whether those symbols were available. When we ported everything to cmake, we decided with @xoofx  that C linking tests would have been better.

> In my opinion, checking everything is desirable, but we need to come up with a good way to reduce the time taken by each testing.

Linking these tests and running them takes a tiny amount of time compared to the `tester` ones.

> If it is better to check if each function works correctly, I think modifying tester3 and checking if the functions return the same values as the non-finite functions is reasonable.

It is not written anywhere that the finite calls shoudl return the same values as the non finite ones. The finite symbols are generated by a compiler  when `-ffast-math` is passed at compile time. We might need to make them faster to compete with `libmvec`, which means they will not behave the same as the non finite ones.

In general, I am keen to keep these tests, and I am also keen in expanding them not only to cover the finite GNUABI names, but the GNU ABI names in general, so that we can claim "on paper" that SLEEF is compatible with the GNUABI. 

The GNUABI names are auto-generated, I don't feel comfortable in leaving the process untested.

**Comment by fpetrogalli-arm** [comment]
Here is how I intend to cover testing of the GNUABI symbols in libsleefgnuabi.

https://github.com/shibatch/sleef/pull/160

I will definitely keep the AArch64 ones in our downstream sources, to avoid surprises at link time when unit testing the HPC compiler.

@shibatch , what do you think? Are you happy for me to proceed in this direction?

**Comment by shibatch** [comment]
What is the reason that you check availability of only a subset of functions?
It is easier to understand if you check all functions.

**Comment by fpetrogalli-arm** [comment]
Adding the remaining function is secondary to checking if the structure is OK for you.

**Comment by shibatch** [comment]
Could you explain the advantage of C linking tests over the test with nm?

**Comment by fpetrogalli-arm** [comment]
The only advantage I can think about is that they work even if `nm` is not available, although I am aware of the fact that `nm` is probably available on all the OSes that need a GNUABI compatible interface.

What is your concern about testing them via the linker?

**Comment by shibatch** [comment]
The main question is what you want to test in the gnuabi test.

If you just want to prevent the case where no symbol is exported due to build failure, then it is sufficient to check if one symbol out of many is exported. In this case, testing with nm would be the simplest.

If you want to check if all symbols are exported, then implementing a generator from funcproto.h and checking if all functions are exported would be good. In this case, we regard funcproto.h as a kind of specification.

If you want to check if all symbols are exported and all the corresponding functions work correctly, then a naive way of testing this is to use the tester. Although the finite calls don't need to return the same values as the non finite ones, we can utilize the fact that they actually share the same implementation and use tester3 to reduce the testing time. When we will change the implementation, we will also change the testing method.

**Comment by fpetrogalli-arm** [comment]
I want to check that all symbols of `libsleefgnuabi.so` are correct, meaning that:

1. they have the same name they would have in `libmvec`
2. they have additional _finite_ version if `libmvec` have one.

The code in #160 is doing both of these, all I need to do is to add the proper DECLARE and CALL macro for each of the functions. For example, checking `sincos` would add:

```
DECLARE_DP(sincos,vl8l8);
// ...
int main (void) {
// ...
CALL_DP(sincos,vl8l8);
// ...
```

I didn't want to auto-generate these names to make sure that the abstraction between the funcproto.h and the auto-generative process that creates the names in `libsleefgnuabi` is correct.

Any auto-generative process around `funcproto.h` would mimic what `mkrename_gnuabi.c` already does.

One day we might even come up with removing the auto-generative process. If that the case, we wouldn't need to rewrite the gnuabi compatibility tests if they are written like in #160.

Currently, the only way I have to test that the symbols that a GNUABI-compatible compiler (clang & gcc) generates are present in libsleefgnuabi is by compiling a bunch of code and fixing any linker failure by adding the symbol in libsleefgnuabi.

This happened, it is not good, and to prevent it happen I need to guard it. A linker mechanism seems the best option to me. Auto-generation could be done, but I believe it would miss part of the testing that is needed to make sure that a specific symbol is in the library. Moreover, explicit testing is easier to read and maintain.

**Comment by fpetrogalli-arm** [comment]
Update: the PR we are discussing is now #161.

**Comment by shibatch** [comment]
Then how about generating the test program from libmvec?

**Comment by shibatch** [comment]
I now checked libmvec on my computer, and I see only 18 symbols exported for SSE.
I think nm is easier?

_ZGVbN2v___exp_finite
_ZGVbN2v___log_finite
_ZGVbN2v_cos
_ZGVbN2v_exp
_ZGVbN2v_log
_ZGVbN2v_sin
_ZGVbN2vv___pow_finite
_ZGVbN2vv_pow
_ZGVbN2vvv_sincos
_ZGVbN4v___expf_finite
_ZGVbN4v___logf_finite
_ZGVbN4v_cosf
_ZGVbN4v_expf
_ZGVbN4v_logf
_ZGVbN4v_sinf
_ZGVbN4vv___powf_finite
_ZGVbN4vv_powf
_ZGVbN4vvv_sincosf

**Comment by fpetrogalli-arm** [comment]
> Then how about generating the test program from libmvec?

No, libmvec differ from system to system.

> I now checked libmvec on my computer, and I see only 18 symbols exported for SSE.
I think nm is easier?

Those are just a subset. In the future libmvec will have as many as we do. We could even have more than `libmvec`.
The file is currently 100 lines. It seems pretty simple to me, most of the code is `detectFeature`, it will grow only of the number of functions I need to test. I will submit a patch with all of them, if this helps in giving you a better view on it.

I came up with a target independent way of testing what I need to test, with no dependencies on mkrename scripts, I think we should keep it. If a non GNUABI-compatible system decide to use those names, we can test it there too without messing around with `cmake` to check an alternative to `nm`.

**Comment by shibatch** [comment]
Okay, please go ahead.

**Comment by fpetrogalli-arm** [comment]
All functions added in #162
