### ISSUE TITLE
Release 3.2

### ISSUE THREAD

**Issue by fpetrogalli-arm** [shibatch/sleef#147]
@shibatch , I think we are ready for the release of 3.2. What do you think?

**Comment by shibatch** [comment]
We are mostly ready. 
We need to decide exactly which PRs are included in 3.2.
Before release of 3.2, we need the following items to be completed.

* Update documents
  * Building the library with cmake
  * Newly exposed functions and aliases
  * Changelog
* Complete the version bump script
  * Make it manage the Debian version

**Comment by fpetrogalli-arm** [comment]
Do we really need the version bump script? Why don't we just agree to fill the changelog according to the syntax specified on top of it?

Also, what do you mean with "manage the Debian version"?

**Comment by shibatch** [comment]
At least we need to remove makefiles.
They are not managed or tested anymore, so they have to be removed.

For the changelog, we need to reflect the current state anyway.

The Debian version is regarding to the files under debian directory.
We need to change the versions in the documents, cmakefile and debian-related files in sync.

I am planning to release 3.2 by the end of January, but are you in a hurry?

**Comment by fpetrogalli-arm** [comment]
> At least we need to remove makefiles.
> They are not managed or tested anymore, so they have to be removed.

Fine, makes sense. But let's hold #146 as the last commit of the release, our downstream builders are still using the Makefiles. I am currently in the process of migrating all CI to cmake, but I want to turn off the Makefile based one only when I am done with the new cmake ones.

> For the changelog, we need to reflect the current state anyway.

Sure, I am just saying that I prefer a hand crafted changelog over a script generated one.

> The Debian version is regarding to the files under debian directory.
> We need to change the versions in the documents, cmakefile and debian-related files in sync.

I am not keen in having this in the repo. We don't ship the library in binary format for debian, why do we care? I think we should get rid of this part.

> I am planning to release 3.2 by the end of January, but are you in a hurry?

No, end of January is fine.

**Comment by shibatch** [comment]
After PR https://github.com/shibatch/sleef/pull/146, https://github.com/shibatch/sleef/pull/150, https://github.com/shibatch/sleef/pull/151 and https://github.com/shibatch/sleef/pull/152 are approved, I will release 3.2.

**Comment by shibatch** [comment]
Yes, the updated document includes new benchmark results.
