### ISSUE TITLE
Development plan toward 3.3

### ISSUE THREAD

**Issue by shibatch** [shibatch/sleef#178]
I am planning to make big changes for version 3.3.
Most of them are already discussed in the issues, but here I list them.

* https://github.com/shibatch/sleef/issues/47 Each math function should return bit-identical results regardless of vector width.
* https://github.com/shibatch/sleef/pull/124 Since we are going to have many helper files, we need to somehow reduce the testing time. The testing at travis is already close to timeout.
* https://github.com/shibatch/sleef/issues/129 In order to cleanup the helper files, I am planning to rename them.
* https://github.com/shibatch/sleef/issues/142 Masked functions are already implemented in the GNUABI version of the library. These will be also implemented in the core library. In addition to that, the helper files will be modified in such a way that SLEEF can utilize the full benefit of masked instructions.

It would be a little tricky to implement all of these while keeping the source code tidy.

**Comment by shibatch** [comment]
@RoyiAvital I overlooked your comment until now, but there is basically no room for exp to get faster. It does not use DD arithmetic, and it should be fast enough already.

**Comment by shibatch** [comment]
It would be also better to add VML-style API to SLEEF.

**Comment by blapie** [comment]
Closing this as SLEEF is way past release 3.3. Issues that were or were not added still exist anyway.
