### ISSUE TITLE
Compilation with CLang under Windows

### ISSUE THREAD

**Issue by RoyiAvital** [shibatch/sleef#184]
According to the table on Sleef web page compilation with Clang won't generate AVX compatible code for Windows x64:

![image](https://user-images.githubusercontent.com/7347975/38479111-cbc3d4ba-3bc5-11e8-8a2c-00d4adaaef1d.png)

Yet if one have a look at:
https://github.com/Alexpux/MSYS2-packages/issues/1209#issuecomment-379576367

Then:

1. Clang output compatible code.
2. If Sleef wouldn't use variables by value even GCC is all good.

I'm trying to raise the GCC issue so people with knowledge will take care of it.

**Comment by RoyiAvital** [comment]
Hi,

Any progress on that?
There is `clang-cl.exe` which should compatible to MSVC.  
Also it allows using flags of CLang using `-XClang -clangFlag` if some flags needed for better performance.

**Comment by shibatch** [comment]
This is not a problem in SLEEF.

**Comment by RoyiAvital** [comment]
If you consider the CMake environment with SLEEF as part of SLEEF than it is.
What's needed is to adapt the CLang related Macros defined in your build system to work on Windows as well.

**Comment by RoyiAvital** [comment]
@shibatch ,
It is a problem of SLEEF.  

You have CLang Compiler in Windows which is fully compatible to CLang in Linux and have full AVX2 support.
You just need to let it be used just like MSVC in CMAKE and also in the Macors in the code.

**Comment by shibatch** [comment]
Clang that comes with visual studio is indicated as experimental.
I don't know under what condition other versions of clang works correctly.
You can use AVX if it works, since it is not disabled. It is just not supported.

**Comment by RoyiAvital** [comment]
I'm not talking on CLang under MSVC (In that case it is only a parser).

I;m talking about [CLang for Windows](http://releases.llvm.org/download.html) which is fully compatible to CLang on any other system.  

All you need to make sure that if the Compiler is CLang under Windows it is treated just like CLang under Linux.

**Comment by RoyiAvital** [comment]
By the way, LLVM 6.x.x ships with Clang for Windows which is MSVC compatible.
Namely you can get the Clang performance just by switching the compiler identifier.

This will give modern OpenMP and high quality compiler in Windows (With proper AVX / AVX2 / AVX512 support).
It should be easy to utilize it.

**Comment by shibatch** [comment]
Could you build sleef with clang on windows and provide the command line for compilation?

**Comment by RoyiAvital** [comment]
The problem is your code is very sensitive to the generator and the compiler.
You added many cases to take care of them and created something which is hard to make portable.

Moreover you make wrong assumptions about the code of LLVM / CLang (Which has no issue with generating AVX code on Windows unlike GCC).

If you make sure you treat Clang just like GCC it will work.

**Comment by shibatch** [comment]
Please write a patch yourself.
I'm not interested.

**Comment by RoyiAvital** [comment]
@shibatch ,
I got you, you don't want Windows users.

I just think that you should fix errors in the page (AVX support has nothing to do with Cygwin, only with GCC, all other compilers support AVX on Windows).
