### ISSUE TITLE
sqrt / sqrtf dependency in sleefdp.c / sleefsp.c

### ISSUE THREAD

**Issue by carlkl** [shibatch/sleef#20]
in several sleef functions standard sqrt/sqrtf math functions are referenced. As xsqrt_u05 / xsqrtf_u05 are defined: why not use this functions to get rid of this references?

BTW: the magic number 0x5fe6ec85e7de30da (sleefdp.c:1665) is not exact according to the wikipedia article.

**Comment by shibatch** [comment]
I want to keep SLEEF practical. The speed of computation is a very important aspect. If I use xsqrt_u05 and xsqrtf_u05, the computation would be too slow.

The reason that I define those two sqrt functions is that I want to say SLEEF supports all C99 math functions. At this time, it lacks a few functions but I am now trying to implement those functions, and it will finish soon.

**Comment by carlkl** [comment]
now: https://github.com/shibatch/sleef/issues/79
