### ISSUE TITLE
Make it easier to auto-generate bindings for the library

### ISSUE THREAD

**Issue by gnzlbg** [shibatch/sleef#206]
Is there a configuration option I can use to disable all `long double`-related functionality ? 

I am trying with `-DCOMPILER_SUPPORTS_LONG_DOUBLE=FALSE` and `-DCOMPILER_SUPPORTS_FLOAT128=FALSE` but I do still get types like `Sleef_longdouble2` in the generated headers.

I do not mind about the library using `long double` internally, but about including it in the exported headers.

**Comment by gnzlbg** [comment]
I am auto-generating sleef bindings for Rust, which does not have a native 80-bit floating point type. 

Not being able to hide the APIs using 80-bit floats makes this task much harder.

I would also like to expose the APIs compiled with different features e.g. I'd like to expose sse2, sse4.2, avx, avx2, and avx-512 versions of `sinf_u1`, but it is unclear to me whether all these versions are currently compiled into the library and their symbols exposed, or whether I have to manually build the library N times for each set of features, merge them somehow, and the wrap that.

**Comment by shibatch** [comment]
>Not being able to hide the APIs using 80-bit floats makes this task much harder.

I don't fully understand what you are trying to do, but simply removing unnecessary lines using grep is not enough?

> it is unclear to me whether all these versions are currently compiled into the library and their symbols exposed, or whether I have to manually build the library N times for each set of features, merge them somehow, and the wrap that.

All the features that can be compiled by the C compiler are compiled in. It does not make sense to build the library multiple times.

**Comment by fpetrogalli-arm** [comment]
> I would also like to expose the APIs compiled with different features e.g. I'd like to expose sse2, sse4.2, avx, avx2, and avx-512 versions of sinf_u1, but it is unclear to me whether all these versions are currently compiled into the library and their symbols exposed, or whether I have to manually build the library N times for each set of features, merge them somehow, and the wrap that.
> 
Hi @gnzlbg,

You have two choices here: you can either call the functions from libsleef, which are mangled according to the scheme in http://sleef.org/x86.xhtml (figure 3.1), or you can use the library libsleefgnuabi which is libmvec (vector math library in glib) and that uses the naming conventions and ABI defined in the Vector Function ABI for x86 [1]. AArch64 has a similar ABI too [2]. The two libraries provide the same list of vector functions.

Francesco

[1] https://sourceware.org/glibc/wiki/libmvec?action=AttachFile&do=view&target=VectorABI.txt
[2] https://developer.arm.com/products/software-development-tools/hpc/arm-compiler-for-hpc/vector-function-abi

**Comment by gnzlbg** [comment]
> but simply removing unnecessary lines using grep is not enough?

Some features span over multiple lines (like the Sleef_long_double2 types), I'd basically have to implement a C language parser to be able to remove them as far as I can tell.

The binding generation library I am using supports ignoring types and functions when generating the bindings, so I am manually just disabling the ones that use the f80 types but I'd appreciate an option to select which APIs to include in the binaries / headers. 

I'd guess people using SLEEF from other languages without f80 (Python, etc.) would run into these issues at some point. This is a task that is relatively easy to accomplish at the library level (hiding these from the generated headers would be enough), but becomes more and more complex up the stack. 

> All the features that can be compiled by the C compiler are compiled in. It does not make sense to build the library multiple times.

Looking at the docs the API for x86 is, for example:

```c
__m128d Sleef_sind2_u10(__m128d a);
__m128d Sleef_sind2_u10sse2(__m128d a);
__m128d Sleef_sind2_u10sse4(__m128d a);
__m128d Sleef_sind2_u10avx2128(__m128d a);
```

Does that mean that those are always available as long as the C compiler supports compiling the feature ? If so, is there an option to enforce that? That is, to say, that I want all those versions in the binary, and if the C compiler doesn't support them, then I should get a build error ? 

I mention this because we would be shipping the sources and compiling them on many different targets and platforms, and diagnosing a missing symbol up the stack is harder than just failing hard while building the library. 

Maybe I could just "disable" the checks by defining them to be true, and if the C compiler does not support a feature, it will just fail to build.

**Comment by gnzlbg** [comment]
FWIW, I am currently generating the bindings to work around a family of LLVM bugs in the Rust std library, where LLVM currently (and for the forseable future) is not able to convert LLVM vector intrinsic calls into library calls (to `libmvec`, `SVML`, `Accelerate`, ...) if these do not originate in loops (and even then, I am not sure how good the current system actually works). 

So once I have nice bindings for SLEEF set up, I'll start replacing LLVM intrinsics calls with SLEEF calls in `https://github.com/rust-lang-nursery/packed_simd` (the `std::simd` module), initially, behind an optional feature. Depending on how well we manage to properly ship and build SLEEF in our target platforms (and how well we are able to cross-compile it), we might eventually turn this on by default (although I plan to allow using SVML and libmvec at some point as well). 

Or at least that's one of the avenues we are exploring to solve this problem.

**Comment by shibatch** [comment]
@gnzlbg Okay, I will implement the feature to disable long double functions.

> Does that mean that those are always available as long as the C compiler supports compiling the feature ?

Yes.

> If so, is there an option to enforce that? That is, to say, that I want all those versions in the binary, and if the C compiler doesn't support them, then I should get a build error ?

There is no such option. I can implement it, though.

>So once I have nice bindings for SLEEF set up, I'll start replacing LLVM intrinsics calls with SLEEF calls in https://github.com/rust-lang-nursery/packed_simd (the std::simd module), initially, behind an optional feature. 

Basically, I am expecting users to use the functions with a dispatcher in the cases like this.

**Comment by gnzlbg** [comment]
@shibatch 

> Basically, I am expecting users to use the functions with a dispatcher in the cases like this.

What do you mean with a dispatcher? 

We can do both static and run-time feature detection in Rust (at least for all relevant features in x86, x86_64, arm32, arm64. ppc64le, and mips64r6). I was planing on using static dispatch here (that is, depending on which features the whole binary is compiled with) but after peeking at the implementation of some functions (like the trigonometric ones) I might do run-time feature detection here since after binary initialization run-time detection is just a single relaxed load on x86_64.

However, from Rust, we statically link against `sleef`, but we call the `sleef` api via "Rust headers". The problem I was talking about happens when, e.g., sleef does not include say the AVX-512 version of a function because the C compiler did not support it, and this happens silently, but we try to call that function from Rust, which doesn't exist. At best, we would get a linker error here, which is pretty bad from an user POV. 

---

@fpetrogalli-arm 

> Interesting. Are those LLVM bugs real bugs of missing features? :) Do you mind sending a link pointing at them?

https://bugs.llvm.org/show_bug.cgi?id=38528

I can't really explain things better than others have explained there. There are many mailing list posts explaining the current design, but in a nutshell, currently, and by design, only the loop vectorizer pass can legalize a call to a vector math operation (e.g. `llvm.sin.v4f32`) to a vector-lib call (e.g. a call to SVML). 

As others mention, that can be fixed, and it might make sense to do so, but without anybody championing the work, I doubt things will change in the short term here. I hope I am wrong.

**Comment by shibatch** [comment]
>What do you mean with a dispatcher?

A dispatcher chooses the best vector extension available on the computer.
If you call Sleef_sind2_u10, it automatically chooses from AVX2, SSE4 or SSE2 implementation according to availability of those extensions.

http://sleef.org/additional.xhtml#dispatcher

>However, from Rust, we statically link against sleef, but we call the sleef api via "Rust headers". The problem I was talking about happens when, e.g., sleef does not include say the AVX-512 version of a function because the C compiler did not support it, and this happens silently, but we try to call that function from Rust, which doesn't exist. At best, we would get a linker error here, which is pretty bad from an user POV.

Okay. I now understand your problem.

**Comment by gnzlbg** [comment]
The following question might be dumb, but I can't fully wrap my head about how the SLEEF ABI works.

How does SLEEF handle ABI mismatches depending on target features ? 

For example, suppose a binary `foo` links against Sleef and calls `__m256d Sleef_sind4_u35(__m256d);`, which is a function that takes a `__m256d`. 

If `foo` was compiled with AVX enabled, the AVX calling convention would pass and return the function argument as a single 256-bit wide register. 

If `foo` was only compiled with SSE4.2 enabled, the SSE calling convention would pass two 128-bit wide registers. 

Depending on how SLEEF was compiled, `Sleef_sind4_u35` might be expecting either one 256-bit wide register, or two 128-bit wide registers. 

I'd assume that ABI mismatch would produce undefined behavior. 

The typically way I've seen to deal with this is to either pass the arguments via memory, or require that SLEEF is compiled with the same target features as the binary where it is used.

Or what am I missing?

**Comment by shibatch** [comment]
> If foo was only compiled with SSE4.2 enabled, the SSE calling convention would pass two 128-bit wide registers.

No. SSE functions only receives and returns 128-bit wide registers. This is same as SVML.

> The typically way I've seen to deal with this is to either pass the arguments via memory, or require that SLEEF is compiled with the same target features as the binary where it is used.

I am planning to implement such a feature. See https://github.com/shibatch/sleef/issues/193.
This will take some time, though.

**Comment by gnzlbg** [comment]
> No. SSE functions only receives and returns 128-bit wide registers. This is same as SVML.

What about functions that do not specify whether they are SSE, or AVX?

Maybe I am misunderstanding things because we talked about "dispatchers" above. 

For example, for `__m256d Sleef_sind4_u35(__m256d)`:

* can I call this function from a translation unit compiled with SSE?
* can I also call it from a translation unit compiled with AVX2? 

IIUC, please correct me if I am wrong, in the translation unit compiled with SSE, `__m256d` will be passed to `Sleef_sind4_u35` as two 128-bit wide registers, but in the translation unit compiled with AVX2, `__m256d` will be passed to `Sleef_sind4_u35` as one single 256-bit wide register. 

Is this correct, or how does SLEEF achieve different behavior ?

**Comment by gnzlbg** [comment]
Ahhh! I think I realized how it works: 

```c++
#ifdef __AVX__

// ...
IMPORT CONST __m256d Sleef_powd4_u10(__m256d, __m256d);
// ...

#endif
```

That is, a translation unit can only call functions using the 256-bit wide vector types if AVX is enabled for the whole translation unit. After the discussion about the dispatcher I thought that it wouldn't work in this way: that is, that a translation unit compiled with SSE should be able to detect at run-time if the CPU supports AVX, and then e.g. change the stride of a loop from 4 to 8 and call the AVX functions instead. However, that is not possible, because the AVX functions are just not exposed via the header if AVX is not enabled for the whole translation unit.
