### ISSUE TITLE
Moving documents to github.io repository

### ISSUE THREAD

**Issue by shibatch** [shibatch/sleef#21]
I am now considering to move the documents to a new repository shibatch.github.io. By doing this, it would be easier for the users to see the documents. The license management would be a little bit troublesome, though. I want to hear comments on this.

**Comment by fpetrogalli-arm** [comment]
What do you exactly mean by documents? The documentation in the `doc` folder? If so, I strongly oppose to this. We should keep the documents as close as possible to the tools / algorithms / functionality they describe.

Having said that, I am happy for you to use github.io to create and maintain a website for SLEEF.

**Comment by shibatch** [comment]
I meant the documentation in the doc folder.
Okay, then I will copy the contents under doc folder to github.io at each release. Is there any problem with this?

**Comment by fpetrogalli-arm** [comment]
No, this is fine.
