### ISSUE TITLE
PPA for sleef

### ISSUE THREAD

**Issue by cdluminate** [shibatch/sleef#222]
As requested:

https://launchpad.net/~lumin0/+archive/ubuntu/sleef
https://launchpad.net/~lumin0/+archive/ubuntu/sleef/+packages

Remaining todo:

- [x] ~~Ubuntu 14.04 is not supported due to `CMake 3.4.3 or higher is required.  You are running version 2.8.12.2`~~
- [x] ~~Ubuntu 16.04 build failure `recompile with -fPIC`~~
- [x] Ubuntu 18.04 Built. (amd64, arm64, armhf, i386, ppc64el, s390x)
- [x] Test the package for bionic (18.04)

**Comment by shibatch** [comment]
Thank you so much.
I think we don't need Ubuntu 16.04 support.
I checked the compilation error with 16.04, and it looks strange.
I have not seen an error like that before.

**Comment by cdluminate** [comment]
@shibatch Then let's ignore Ubuntu 14.04 and 16.04 . I've checked the package for bionic/amd64, and it is working. (hellox86.c compiled and worked)

**Comment by fpetrogalli-arm** [comment]
@cdluminate what is the status of this issue? If it is done, can you link the pages of the remaining builds?

**Comment by cdluminate** [comment]
@fpetrogalli-arm Ubuntu (>= 19.04) ships sleef already so any future version won't need this PPA. And the package for Bionic (18.04) is already in the PPA. So I think this issue can be closed.

**Comment by fpetrogalli-arm** [comment]
Thank you. Specifically, are you shipping `libsleef.so`, or `libsleefgnuabi`, or both?

**Comment by cdluminate** [comment]
@fpetrogalli-arm IIRC both
