### ISSUE TITLE
AArch64: -march=armv8-a+simd is incorrect

### ISSUE THREAD

**Issue by steleman** [shibatch/sleef#232]
This is based on sleef 3.3.1:

The cmake file Configure.cmake contains the following:

```
set(CLANG_FLAGS_ENABLE_NEON32 "--target=arm-linux-gnueabihf;-mcpu=cortex-a8")
# Arm AArch64 vector extensions.
set(CLANG_FLAGS_ENABLE_ADVSIMD "-march=armv8-a+simd")
```

This -march option is incorrect and unnecessary. It causes conflicts with -mcpu.

For example, GCC correctly warns if -mcpu=thunderx2t99 -march=armv8-a+simd was passed on compile-line:

```
%> cat t.c
#include <stdio.h>

int main()
{
    return 0;
}
```

```
%> gcc --version
gcc (GCC) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
[ ... ]
%> gcc -O3 -std=c99 -mcpu=thunderx2t99 -march=armv8-a+simd t.c -o t
cc1: warning: switch -mcpu=armv8.1-a conflicts with -march=armv8-a switch
```

Furthermore, this encourages building sleef without passing -mcpu=[X] on compile-line. Without -mcpu, the compiler will always choose the default generic instruction scheduler, which will lead to very poor performance on some AArch64 CPUs. For example on T99.

-mcpu=[X] is sufficient and should be required in CFLAGS. Either the particular AArch64 micro-arch can do V8 SIMD, or it can't. If it can do V8 SIMD, it will be available by default, without the need to pass -march=armv8-a+simd on compile-line.

**Comment by fpetrogalli-arm** [comment]
Fixed in https://github.com/shibatch/sleef/commit/8e6e52f2153168ea7f7611076b6f077ea63003ac. Thank you @shibatch .
