### ISSUE TITLE
Add a vectorized quadruple precision math library

### ISSUE THREAD

**Issue by shibatch** [shibatch/sleef#233]
I am planning to add a vectorized quadruple precision math library to SLEEF. This is basically to add a quadruple precision version of the math functions in SLEEF.

This library is added as a new subproject of SLEEF. The existing subprojects won't be affected much.

The format of the FP number will basically comform to IEEE 754 quadruple-precision binary FP format. It will support denormal numbers, NaN and Infinity.

The computation methods are backed by triple-double arithmetic(TD). The subroutines basically first converts the argument in IEEE format to TD, evaluates the function in TD, and converts the result back to IEEE format. TD is a lot faster than computing in IEEE format, since packing to/unpacking from IEEE format is tricky and time consuming.

The library also includes subroutines for basic arithmetic operations(i.e. add, mul, div, compare and cast). At this point, I only have those routines backed by TD, and thus they are not fast, nor perfectly correctly rounded(their error bound is like 0.5000000001 ULP). I need to implement subroutines with direct computation methods in order to make them faster and correctly rounded.

The library will define new data types like the following. When a 128-bit vector extension, this data structure is basically a concatenation of two QP floating-point number.

```
typedef struct {
  vmask x, y;
} Sleef_quad2;
```

With 128-bit vector, they compute two QP values at a time. With purec helper, they compute one QP value.

It will define functions like the following.

```
Sleef_quad2 Sleef_sqrtq2_u05sse2(Sleef_quad2 a);

Sleef_quad Sleef_addq1_u05purec(Sleef_quad a, Sleef_quad b);
Sleef_quad2 Sleef_addq2_u05sse2(Sleef_quad2 a, Sleef_quad2 b);

__m128i Sleef_cmpltq2_sse2(Sleef_quad2 a, Sleef_quad2 b);

__m128d Sleef_castdq2_sse2(Sleef_quad2 a);
Sleef_quad2 Sleef_castqd2_sse2(__m128d a);
```

It will also define utility functions for converting from/to a string.

```
Sleef_quad Sleef_strtoq(const char *nptr, char **endptr, int base);
void Sleef_qtostr(char *s, size_t n, Sleef_quad a, int base);
```

The subroutine will contain tester and tester2, which correspond to the existing ones.

**Comment by fpetrogalli-arm** [comment]
@shibatch , can we consider this done after #235 ? Or do you plan to add more functions?

**Comment by shibatch** [comment]
I think it is okay to close this issue.
I will add more functions to libsleefquad, but that's not the point of this issue.
