### ISSUE TITLE
fma functions does not simply use fma instructions when available

### ISSUE THREAD

**Issue by yuyichao** [shibatch/sleef#244]
I was really surprised to see that functions like `Sleef_fmad2_avx2128` does not simply use one `fma` instruction and return, even though it seems to be using `fma` instruction in the implementation.
Is this just an oversight or is there any deep reasons behind this? If this is intentional, it should probably be documented I found it a bit confusing and did a github search without finding anything...

**Comment by shibatch** [comment]
Some functions are not well optimized.

**Comment by shibatch** [comment]
As for fma function, the compiler should emit an fma instruction instead of a call to fma function. So, this should be a compiler problem rather than a problem of the library.

**Comment by yuyichao** [comment]
So what's the point of the `Sleef_fmad2_avx2128` (and other) functions, if the user is not expected to ever use them?

Also, this affect the dispatch version, i.e. `Sleef_fmad2`, I don't think the compiler (for the user code) is responsible for the optimization in such case even if it gained full knowledge of the sleef library.

**Comment by shibatch** [comment]
> So what's the point of the Sleef_fmad2_avx2128 (and other) functions, if the user is not expected to ever use them?

I just wanted to claim that sleef implements all FP functions in the C99 standard.

> Also, this affect the dispatch version, i.e. Sleef_fmad2, I don't think the compiler (for the user code) is responsible for the optimization in such case even if it gained full knowledge of the sleef library.

Okay, I will fix this. This is not the only function that is not well optimized.

**Comment by yuyichao** [comment]
> I just wanted to claim that sleef implements all FP functions in the C99 standard.

OK sure...

> This is not the only function that is not well optimized.

Fine. This does seem like a very easy one though, at least in terms of the actual implementation, not necessarily in terms of the conditional compilations needed...

On the related note, is there a list of functions that **is** well optimized?

**Comment by shibatch** [comment]
> On the related note, is there a list of functions that is well optimized?

The functions on the benchmark graph are well optimized.

https://sleef.org/benchmark.xhtml

**Comment by yuyichao** [comment]
K, that's a shorter list than I wished but it does cover most of the important ones. (no hyperbolic functions though...)

**Comment by shibatch** [comment]
Hyperbolic functions should not be very slow.
If you are to use those functions in machine learning, please try 3.5-ulp versions, which I recently added.

**Comment by shibatch** [comment]
This is implemented in PR https://github.com/shibatch/sleef/pull/297.
