### ISSUE TITLE
add exp10 function

### ISSUE THREAD

**Issue by musm** [shibatch/sleef#26]
pretty trivial to add since all the pieces are already there

**Comment by shibatch** [comment]
exp10 is already there.
I think what is lacking is log2?

**Comment by musm** [comment]
ah missed that, yes

**Comment by musm** [comment]
btw exp2 is pretty slow compared to openlibm which just uses a table since  the exponentiation is very small

**Comment by shibatch** [comment]
I want to see statistics on how frequently each function is used.
