### ISSUE TITLE
FMA4 detection is wrong

### ISSUE THREAD

**Issue by colesbury** [shibatch/sleef#261]
The FMA4 detection currently checks bit 16 of register EDX. It should be bit 16 of register ECX i.e. `reg[2]` :

https://github.com/shibatch/sleef/blob/5d84bbf1455d6fd4a9d08612ec87245935e5f374/src/arch/helperavx.h#L67-L71

```
reg[0] = eax
reg[1] = ebx
reg[2] = ecx
reg[3] = edx
```

Here's the dissasembly for Sleef_x86CpuID:

```
Dump of assembler code for function Sleef_x86CpuID:
   0x00007fffe13d80d0 <+0>:     push   %rbx
   0x00007fffe13d80d1 <+1>:     mov    %esi,%eax
   0x00007fffe13d80d3 <+3>:     mov    %edx,%ecx
   0x00007fffe13d80d5 <+5>:     cpuid
   0x00007fffe13d80d7 <+7>:     mov    %ebx,0x4(%rdi)
   0x00007fffe13d80da <+10>:    mov    %eax,(%rdi)
   0x00007fffe13d80dc <+12>:    mov    %ecx,0x8(%rdi)
   0x00007fffe13d80df <+15>:    mov    %edx,0xc(%rdi)
   0x00007fffe13d80e2 <+18>:    pop    %rbx
   0x00007fffe13d80e3 <+19>:    retq
```

This leads to crashes on some CPUs that don't support FMA4 (and don't support newer instruction sets like AVX2). For example: https://github.com/pytorch/pytorch/issues/12112#issuecomment-491521239

**Comment by ezyang** [comment]
@colesbury It doesn't look like you actually opened a PR with the fix on sleef repository

**Comment by colesbury** [comment]
@ezyang yes. I want to verify that this fixes the "Illegal Instruction" issue first, but our nightly builds either failed or haven't finished yet for Linux.
