### ISSUE TITLE
Documentation: compilation with GCC

### ISSUE THREAD

**Issue by gdonval** [shibatch/sleef#263]
I'm currently trying to use the GNU abi compatible variant of SLEEF as a replacement for libmvec in an HPC system (old OS, ancient glibc/libm, new nodes with AVX512f support).

### What I have done

* I am using GCC 7, 
* I have compiled all the "smartly-dispatched" library dependencies **without** sleef (i.e. libraries like FFTW). 
* I have built the final program with sleef by adding ``-lsleefgnuabi`` in the linker flags and I made sure that it appeared **before** ``-lm``.
* I have tried both static and dynamic linking.

### Result

* I am seeing no difference in speed compared to libm (1% difference on single runs, far less on average of multiple runs).
* AVX512- and AVX2-optimized programs are twice as slow as AVX-optimised functions on the AVX512 nodes.

My libm SIMD support stops at AVX, incidentally, which makes me think that sleef functions are simply not called.

### Feature requests

* If linking ``-lsleefgnuabi`` as described isn't correct, I would love to hear how it should properly be done. I can summarize the process in a PR to enhance documentation if needed.
* If everything does look fine, would it be possible to provide a SVML compatibility layer? (I know there's been discussions about that already) SVML functions are not implemented in libmvec: failure would be guaranteed if sleef is not properly linked (instead of silently falling back to libmvec).

**Comment by shibatch** [comment]
Hello @gdonval ,

gnuabi version of sleef does not have a dispatcher.
glibc has a vectorized libm called libmvec.
You have to make sure that libsleefgnuabi is called, instead of libmvec.
You need to specify -ffast-math option to gcc in order to make gcc call the vectorized libm.
So, actually it’s not so simple.

**Comment by gdonval** [comment]
> You have to make sure that libsleefgnuabi is called, instead of libmvec.

That's indeed my problem! (hence the comment about SVML).

> You need to specify -ffast-math option to gcc in order to make gcc call the vectorized libm.

Of course I'm using it! I'm sorry I didn't mention it. Here are my flags for the program (**not** to compile sleef, only to compile the final program making use of sleef):

```
CFLAGS="-march=skylake-avx512 -mtune=skylake-avx512 -ftree-vectorize -fPIC -fno-plt -O3 -ffast-math -flto=8 -Wl,-flto=8 -fno-fat-lto-objects -fuse-linker-plugin -fgraphite-identity -floop-nest-optimize -ffunction-sections"
LDFLAGS="$CFLAGS -flto=8 -Wl,-flto=8 -lsleefgnuabi -lfftw3f -lopenblas -lhwloc -lpthread -lrt -lm"
```
The order is strictly kept.

**Comment by shibatch** [comment]
Did you check if your code is vectorized by gcc?

**Comment by gdonval** [comment]
Well, yes. The code in question is Gromacs by the way. 

* I indeed get AVX-specific assembly instructions all over the place in the AVX-optimized version (all good): that program is fast, even on the AVX512 nodes.
* I do get vectorized instructions in the AVX512-optimized code (vmulps and the like) **however** that version is much slower than the AVX one above.

**Comment by shibatch** [comment]
Most of the computation time is spent for fft in gromacs, so I think sleef does not make so much difference.

**Comment by gdonval** [comment]
Hang on. I have unearthed this: https://gcc.gnu.org/ml/gcc-patches/2018-07/msg00651.html

It would nicely explain pretty much everything, especially why ``-march=ivybridge -mtune=ivybridge`` gives binaries that are twice faster on skylake (than ``-march=skylake-avx512 -mtune=skylake-avx512``).
 
I'm currently recompiling gromacs with ``-mtune=haswell``

**Comment by gdonval** [comment]
> Most of the computation time is spent for fft in gromacs, so I think sleef does not make so much difference.

You are absolutely correct. This is why before coming here, I had recompiled an AVX-specific version of FFTW that I used with AVX- and AVX512-optimized versions of gromacs. The AVX512 binary was still twice as slow. I did the same with openblas. So I assumed that the problem was coming from libm, hence my discovery and use of sleef.

**Comment by shibatch** [comment]
As for adding a SVML-compatible version, please make a separate issue.

**Comment by gdonval** [comment]
Documentation was fine: I used ``sleefgnuabi`` correctly. Closing.
