### ISSUE TITLE
xtan at -0.0

### ISSUE THREAD

**Issue by musm** [shibatch/sleef#29]
https://github.com/shibatch/sleef/blob/master/src/libm/sleefdp.c#L1192
should be
`if (!xisinff(d) && (xisnegzerof(d) || fabsfk(d) > TRIGRANGEMAXf)) u = -0.0f;` 
right?
I don't get  tan(-0.0) = -0.0

similarly for the float version

**Comment by shibatch** [comment]
It gives the correct sign on my environment. Strange.
The tester should be testing if the sign of zero is correct.

**Comment by musm** [comment]
Ah sorry I think I had a mistake in my code, yes it return the correct sign
