### ISSUE TITLE
Suggestion: extern "C" declarations

### ISSUE THREAD

**Issue by dnbaker** [shibatch/sleef#298]
Hi,

It would be convenient for me if the headers (sleef.h/sleefdft.h) were wrapped with `extern "C" {}` declarations, as this sometimes causes linking errors in C++ unless I wrap the includes in that declaration. It's not difficult, but it would be a useful feature.

Thanks,

Daniel

**Comment by dnbaker** [comment]
Following up on this, I can update sleefdft.h easily (see [this](https://github.com/dnbaker/sleef) fork), but header guards are still required around Sleef for Sleef_malloc and Sleef_free.

**Comment by shibatch** [comment]
Merged.
