### ISSUE TITLE
log functions not accurate for denormals

### ISSUE THREAD

**Issue by musm** [shibatch/sleef#3]
e.g. log_u1  for small denormals not accurate to within 1 ulp.

**Comment by shibatch** [comment]
Thank you so much for reporting bugs.
A quick fix might be replacing the following line
e = ilogbp1(d * 0.7071);
with the following.
e = ilogbp1(d * 1.4142)-1;
I will check if this change has adverse effects.

**Comment by shibatch** [comment]
This should be now fixed in version 2.90.
