### ISSUE TITLE
error while using Cmake 3.5.1 

### ISSUE THREAD

**Issue by quickwritereader** [shibatch/sleef#324]
My Pr for Pytorch fails when it is built with CMake versions 3.5.1 on this line  [Configure.cmake:419](https://github.com/shibatch/sleef/blob/master/Configure.cmake#L419)  

I believe It happens because of the below operators as they were added in the later versions
```
VERSION_GREATER_EQUAL
VERSION_LESS_EQUAL
```
A possible fix could be such:
`CMAKE_C_COMPILER_VERSION VERSION_GREATER 9.3 AND CMAKE_C_COMPILER_VERSION VERSION_LESS 10.2`

thanks

**Comment by shibatch** [comment]
Fixed.  https://github.com/shibatch/sleef/pull/325
