### ISSUE TITLE
Pytorch UndefinedSanitizer  sleefsimddp.c:303:49: runtime error: left shift of 4095 by 20 places cannot be represented in type 'int'

### ISSUE THREAD

**Issue by quickwritereader** [shibatch/sleef#326]
@shibatch Thanks for fixing cmake 3,5,1 error
I am getting this error for the latest commit for my PR.

Aug 26 09:10:04   test_mvlgamma_p=1_cpu (__main__.TestAutogradDeviceTypeCPU) ... /var/lib/jenkins/workspace/third_party/sleef/src/libm/sleefsimddp.c:303:49: runtime error: left shift of 4095 by 20 places cannot be represented in type 'int'
Aug 26 09:10:05     #0 0x7f0d522dc80b in Sleef_lgammad4_u10avx

**Comment by shibatch** [comment]
Do you know the version of sleef?

**Comment by quickwritereader** [comment]
Its the latest master commit

**Comment by shibatch** [comment]
At least some of the errors generated by the undefined-bahavior sanitizer seem to be false positives.
I cannot fix all of them.

**Comment by quickwritereader** [comment]
@shibatch thank you.
I will then just try to add ubsan suppressers.
