### ISSUE TITLE
How to get sleef.h file?

### ISSUE THREAD

**Issue by guoqiangqi** [shibatch/sleef#347]
I noticed that the suorce code have included sleef.h file which i can`t find in this project ,should i build the source code to get it or not ?

**Comment by shibatch** [comment]
You have to build the library.
sleef.h is generated when the library is built.

**Comment by guoqiangqi** [comment]
@shibatch  thanks,in fact ,i want to see the implementation of ```Sleef_sind2_u10``` op whcih called by [benchsleef128.c#L45](https://github.com/shibatch/sleef/blob/master/src/libm-benchmarks/benchsleef128.c#L45) ,and i think the function should defined in the source code so that we can build the lib,but i failed to find the implementation.

**Comment by shibatch** [comment]
The implementation is xsin_u1 function in src/libm/sleefsimddp.c.

**Comment by guoqiangqi** [comment]
@shibatch got it and thanks again.

**Comment by shibatch** [comment]
My pleasure.
