### ISSUE TITLE
Doxygen documentation

### ISSUE THREAD

**Issue by fpetrogalli** [shibatch/sleef#35]
As part of the LLVM- compatibility effort, we decided to move SLEEF documentation to `doxygen`.

This task is the initial experimental support for doxygen.

We are not sure that this is what we want to use for the project, therefore to avoid wasting time we limit the scope of this initial investigation to the following:

1. add doxygen documentation only in `sleefsimddp.c`
2. add the docs only for `sin`, `cos`, and `exp`. For each functions, add the precision and the range where this precision is valid.
3. create a `cmake` configuration to build the documentation as the `make docs` target. That should required:
    * a `CMakeLists.txt` configuration file in the `doc` folder with the definitiona of the `docs` target that invokes `doxygen`.
    * a `CMakeLists.txt` in the root folder that will include the `doc` folder.

Once we are happy with this configuration, we can think at extending it to the whole library.

**Comment by blapie** [comment]
I don't think this has been implemented. We are currently markdown docs/reference rendered to html in both github and website.
