### ISSUE TITLE
Are there any real workloads in which vectorized libm functions are needed?

### ISSUE THREAD

**Issue by kangshan0910** [shibatch/sleef#352]
Hi,
I wonder are there any real workloads in which vectorized libm functions such as sin or cos... are needed?

**Comment by shibatch** [comment]
Hello,
I don't understand your question, but the vectorizers in today's compilers find math functions that can be executed in parallel, and thus vectorized math functions are frequently utilized. See the following page.

https://github.com/shibatch/sleef/wiki/Examples-of-auto-vectorizable-codes

**Comment by kangshan0910** [comment]
@shibatch Thanks for your reply. I will study it.
