### ISSUE TITLE
question about helperadvsimd.h

### ISSUE THREAD

**Issue by longbiao7498** [shibatch/sleef#354]
the implementation of vgt_vi2_vi2_vi2 in advsimd is vcgeq_s32, but not vcgtq_s32, is there any problem?  
`  
static INLINE VECTOR_CC vint2 vgt_vi2_vi2_vi2(vint2 x, vint2 y) {    
  return vreinterpretq_s32_u32(vcgeq_s32(x, y));    
}    
`

**Comment by shibatch** [comment]
Sounds like a bug. I will fix it. Thanks.

**Comment by shibatch** [comment]
Merged
