### ISSUE TITLE
Runtime error due to overflow of int

### ISSUE THREAD

**Issue by elfringham** [shibatch/sleef#356]
Checkout of sleef 3.5.1 for the below error message although this error is much older and is still in HEAD, but now at line 329.

/var/lib/jenkins/workspace/third_party/sleef/src/libm/sleefsimddp.c:303:49: runtime error: left shift of 4095 by 20 places cannot be represented in type 'int'

The line is
q = vand_vi_vi_vi(q, vcast_vi_i(((1 << 12)-1) << 20));
which is trying to left shift 4095 by 20 places. This will of course result in shifting into the sign bit of an int.

**Comment by shibatch** [comment]
Is this same as the following issue?

https://github.com/shibatch/sleef/issues/326

**Comment by elfringham** [comment]
Yes, it looks like the same reported issue. I am surprised that it was closed without being fixed. It seems a clear case of undefined behaviour.

**Comment by shibatch** [comment]
I can fix this specific line, but there are many places where the same kind of operations are used.
This is a SIMD library, and thus it sometimes computes unnecessary values which are later discarded.

**Comment by elfringham** [comment]
Please do fix this line.

Thank you.

**Comment by elfringham** [comment]
Dup of #355
