### ISSUE TITLE
Build SLEEF (scalar version) with cmake

### ISSUE THREAD

**Issue by fpetrogalli-arm** [shibatch/sleef#39]
Here is the design I discuss with @diaena:

1. Build the shared object file `libsleef.so` out of `sleefsp.c` and `sleefdp.c`. For the moment, we can live with a single `CMakeLists.txt` script in `src/libm`.
2. Provide a `sleef.h` header file which exports the un-mangled names of the functions, as in `xsin` for the double precision SIN function, and adds the `Sleef_*` names mapped in  `rename.h` [1] as function attribute "alias" [2].
3. Configure `.travis.yml` to execute the cmake build of the library as an additional step
4. Start a `build-with-cmake.md` document in the `doc` folder.

When this is done, we can add the `sleefdl.c` and `sleefqp.c` to the scalar library, but I will create a separate issue for that.

@shibatch , @hfinkel: let us know if you have any questions.

Francesco

[1] https://github.com/shibatch/sleef/blob/master/src/libm/rename.h
[2] https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#Common-Function-Attributes

**Comment by shibatch** [comment]
I don't understand why you need alias attribute. There will be two names for xsin?

**Comment by fpetrogalli-arm** [comment]
@shibatch yes, this will produce two names. I would prefer to expose `xsin` over `Sleef_sin_u35`, as it would make easier for a user to use it. Unfortunately it seems that the alias mechanism doesn't work on OSX, so for now we will not use this functionality.

Are you happy to expose just `xsin`-type names for now? (The idea is then to use the ABI mangled names for the vector versions). Note that  using the alias mechanism would allow to have as many names as we would like for each function - unfortunately the alias mechanism doesn't seems to be portable across the OS that SLEEF supports.

@diaena : I have changed the steps as follows:

1. Build the shared object file `libsleef.so` out of `sleefsp.c` and `sleefdp.c`. Place CMakeLists.txt` script in `src` and recursively in the folders that are needed to build the library.
2. Provide a `sleef.h` header file which exports the un-mangled names of the functions, as in `xsin` (we can change these names if @shibatch prefers to do so).
3. Configure `.travis.yml` to execute the cmake build of the library as an additional step
4. Start a `build-with-cmake.md` document in the `doc` folder.

**Comment by shibatch** [comment]
I have been always thinking that xsin-type name is experimental. Its naming convention is not strictly defined. I was rather thinking, for example Sleef_sin_u10 to have an alias of Sleef_sin, so that users just need to add Sleef_ in front of the standard math function name to get the corresponding function name for sleef. The vectorized function name is also easy, which is like Sleef_sind2 for 128bit function.

If alias doesn't work on OSX, I think we can just switch to macro only on OSX.

**Comment by fpetrogalli-arm** [comment]
I like your idea, let's use the `sleef_sin` names (lowercase, just be consistent with the fact that `sin` is lowercase).

So, we convert `x[name]` into `sleef_[name]`. For now, let's assume this is the unique name we expose the scalar functions.

Note that this mean that `xsin` will be renames as `sleef_sin`, not as `sleef_sin_u35`, while `xsin_u10` will become `sleef_sin_u10`. I'd rather avoid the `_u35`-like post-fixes if they are not specified in the name given in the `.c` file.

For the vectorized version, I think that your naming convention is not enough, as you need to distinguish not only the number of lanes, but also which target vector extension they are providing. The vector ABI already does that. I strongly recommend using the vector ABI name. It might look a bit unnatural, but it can be easily parsed by the compiler to enable auto-vectorization. 

We have to options:

1. We don't want to expose the vector version to the user. In this case, we just go with the Vector ABI names. Only compilers will need to use them, so there is no need for them to be anything other than the vector ABI ones.
2. We want to expose the vector routines to the users: in that case we can sume up with the names `sleef_sin_2d_advsimd` or similar, and since 1. is still needed, we will have to do it using macros and not aliases.

The vector naming convention(s) is anyway something that we need to provide after fixing this issue, so let's postpone the decision for now.

**Comment by shibatch** [comment]
I think we should always make 1-ulp accuracy versions of the functions default. Average users don't want to check if their programs work when accuracy is decreased. It is good idea, though, to make the default function changes if  -ffast-math compiler option is specified.

Target vector extension needs not be specified, since we can call functions with a dispatcher.

Vector-abi names should be definitely exposed, but the question is which scalar functions they correspond to. There is no problem if Vector-abi names corresponding to sleef_* type are exposed. But if we think about exposing vector-abi names corresponding to the standard math functions, as we are doing currently, that library should be separated.

My idea is that the library exposes sleef_* type vector functions and vector-abi functions corresponding to sleef_* type scalar functions. We also need a separated library that exposes vector-abi functions that corresponds to the standard math functions.

**Comment by fpetrogalli-arm** [comment]
What about using only `libm` names and building a library for each of the ULP error we provide?

It would probably make more sense linking against different libraries rather than using `-ffast-math` to choose the precision of the functions. In fact, the `-ffast-math` option sets a set of flags [1] which I don't think correspond to the lower precision concept we have in sleef, as `u35`.

By doing so, we would end up with `libsleef10.so` (or `libsleef.so` if 1ULP is implicit), `libsleef35.so`, and so on, all of them with `libm` names in them. The public header file exposing the names can be the same for each of the library, with macros defining which subset of `libm` is provided for a given precision. This would be easier to handle by a compiler, because a single compile time option could be used do select the version of the library (implying the name of the `.so` file to pass to the linker and which of the math routines are available by setting the macro that selects the subset).

Does that make sense? I prefer this as it avoids the need of finding a way of mangling the concept of ULP error in the name of the function, but still it would make it available to a compiler using the standard pre-processor macro and linker mechanism.

@shibatch , @hfinkel , I'd like to hear from you what you think. 

[1] `-fno-math-errno, -funsafe-math-optimizations, -ffinite-math-only, -fno-rounding-math, -fno-signaling-nans, -fcx-limited-range and -fexcess-precision=fast`, see 
https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#Optimize-Options

**Comment by shibatch** [comment]
If sleef can only be used with libm names, there are a few problems.

* Users might want to use sleef only for vectorized functions, but not the scalar functions.
* Function names for vectorized functions are not human-friendly.
* Vectorized abi is not defined for all vector extensions. Do all functions reference the functions with dispatcher?

It is okay if sleef_* type names can be used with a separate library. At this point, we should provide more choices to the users.

**Comment by shibatch** [comment]
If we want a simple way for the compiler to choose accuracy of the functions, I agree that it is a good idea to make separate libraries that expose the same names. In that case, I would make a  standard-accuracy version and a fast-math version.

**Comment by fpetrogalli-arm** [comment]
Great - let's plan this change once the `cmake` system will have replaced the `Makefile`s one.

Thank you!

**Comment by fpetrogalli-arm** [comment]
@Naoki, @diaena , I think we should develop this transition from Makefile to cmake on a separate branch, say `cmake-transition`. What do you think? Patches related to the cmake system would get merged against `cmake-transition`, and when in we have reached the same degree of functionality of the cmake system with the Makefile one we merge `cmake-transition` into `master`. What do you think? Does it make sense?

As for the naming - with this criteria of getting the same level of functionality, I think we can live with the current names and think about changing them later, when we are sure that the `cmake` builds provide the same functionality of the Makefile one.

**Comment by shibatch** [comment]
Yes, that would be better. You can also check if travis works by doing so.

**Comment by fpetrogalli-arm** [comment]
OK, so I proceed with the new branch. I'll report back here when done.

**Comment by fpetrogalli-arm** [comment]
A branch named `cmake-transition` is live. Please submit `cmake`-related  patches against this branch.

**Comment by fpetrogalli-arm** [comment]
The serial version is in as #40.
