### ISSUE TITLE
CMake package?

### ISSUE THREAD

**Issue by friendlyanon** [shibatch/sleef#411]
This library at the moment provides no CMake package config files in its dev component, so that makes it inconvenient to reuse in another CMake project.

Is there a reason this is not provided?  
If it's just about the lack of experience with CMake, then I can make a PR to add the necessary `install()` commands that generate a CMake package config for the library.

**Comment by shibatch** [comment]
There is no reason. I don't have good knowledge on CMake.
Please contribute.
