### ISSUE TITLE
[question] Support of RISC-V extension V

### ISSUE THREAD

**Issue by gquintin** [shibatch/sleef#432]
Hi, is there any plan to support RISC-V extension "V"?

Intrinsics are available --> <https://github.com/riscv/rvv-intrinsic-doc>
A cross compiler and an emulator is available in the official github of RISC-V --> <https://github.com/riscv>

Compiling and installing all of this can be a little annoying therefore I wrote a small installation script --> <https://github.com/agenium-scale/nstools/blob/master/installation-scripts/install-riscv.sh>

**Comment by shibatch** [comment]
Hello,

When the necessary tools are ready, porting can be started.
But I would wait until the intrinsics can be used with the official clang or gcc.

**Comment by blapie** [comment]
Closing this issue since #477 was just merged.
