### ISSUE TITLE
Hi, is there any plan to support SVE floating-point acceleration instruction in sleef(SVE implementation)

### ISSUE THREAD

**Issue by longbiao7498** [shibatch/sleef#437]
Hi, is there any plan to support SVE floating-point acceleration instruction in sleef(SVE implementation), like [FEXPA/FTSMUL/FTSSEL/FTMAD](https://developer.arm.com/documentation/ddi0596/2021-03/SVE-Instructions/FTMAD--Floating-point-trigonometric-multiply-add-coefficient-). @shibatch

I have implemented simple sin/cos function for Sleef sve version with FTSMUL/FTSSEL/FTMAD Instruction, but I can't understand [FEXPA Instruction](https://developer.arm.com/documentation/ddi0596/2020-12/SVE-Instructions/FEXPA--Floating-point-exponential-accelerator-) , is there any documentation abut FEXPA. @fpetrogalli

**Comment by shibatch** [comment]
Those instructions do not help so much. Evaluation of elementary functions
is not just evaluation of polynomials.

**Comment by longbiao7498** [comment]
0
