### ISSUE TITLE
Monotonicity of functions?

### ISSUE THREAD

**Issue by moon-chilled** [shibatch/sleef#441]
Hi,

I noticed sleef makes some guarantees about precision (usually max 0.5, 1, or 3.5 ulp error).  Is it also guaranteed to be monotonic (where that would make sense)?  E.G. can you ever have x<y but sqrt(x)>sqrt(y)?

**Comment by shibatch** [comment]
There is no guarantee on monotonicity.

**Comment by moon-chilled** [comment]
ok, thanks
