### ISSUE TITLE
questions regarding determinism

### ISSUE THREAD

**Issue by moon-chilled** [shibatch/sleef#443]
1. Are the scalar functions deterministic?

2. If so, are the vector functions guaranteed to give the same results as the scalar functions (given DETERMINISTIC)?

3. Are there plans to add deterministic versions of exp and pow?

**Comment by shibatch** [comment]
Deterministic functions are functions with _cinz_ or _finz_ in their names.

SLEEF has deterministic scalar functions. For example,

*double**Sleef_cinz_powd1_u10purec*(*double*/a/,*double*/b/);

is a deterministic scalar pow function.

Deterministic vector functions return the same results as deterministic 
scalar functions.

**Comment by blapie** [comment]
I believe the question was answered, let us know if you have any further questions regarding determinism.
