### ISSUE TITLE
Why is it recommended to compile with -ffp-contract?

### ISSUE THREAD

**Issue by PierreBlanchard** [shibatch/sleef#456]
Hello,
What is the actual reason compilation with `-ffp-contract=off` is recommended? Is it mandatory?
Is it simply to allow reproducibility across architectures?
What consequences would be expected from enabling `-ffp-contract=fast`?
Would it be a problem at all if the library was always run on fma-enabled architectures? 

Best regards

**Comment by shibatch** [comment]
It will simply not work with -ffp-contract=fast. The library is designed to
compute the error of each fp operation, and -fp-contract=fast breaks that
mechanism.

**Comment by shibatch** [comment]
I don’t know. It depends on the design.

**Comment by blapie** [comment]
Got my answer! Thanks!
