### ISSUE TITLE
Add CI on Windows machines

### ISSUE THREAD

**Issue by fpetrogalli-arm** [shibatch/sleef#48]
Appveyor provides CI on windows machines for open source projects, and it is integrated with github.

It provides "Visual Studio , LLVM/Clang, MinGW and MinGW-w64 compiler infrastructures": https://www.appveyor.com/docs/lang/cpp/

The idea is similar to travis-ci, the build is triggered on new commit via a YAML configuration file. Thank you @rofirrim for pointing this out!

**Comment by shibatch** [comment]
Sounds good to me.

**Comment by fpetrogalli-arm** [comment]
Given that we are moving from Makefile to `cmake`, I think we can save some time by doing this directly in the `cmake-transition` branch.

**Comment by shibatch** [comment]
So, we should make 3.1 branch and cmake-transition branch will be merged to the trunk after it finishes.

**Comment by fpetrogalli-arm** [comment]
Sorry, I don't understand why you want to make a 3.1 branch.

**Comment by shibatch** [comment]
Because there is still possibility to release 3.1.2.
I think it is better to separate 3.1 branch from the trunk, where development for 3.2 takes place.

**Comment by fpetrogalli-arm** [comment]
This is done in #70 , closing.
