### ISSUE TITLE
Please, create tag release

### ISSUE THREAD

**Issue by xypron** [shibatch/sleef#495]
Linux distros typically base their packaging on tag releases. While sleef has been developed continuously no tag has been created since 2020. Therefore sleef is outdated in many distros. E.g. riscv64 builds are missing.

Best regards

Heinrich

**Comment by blapie** [comment]
Hello,

We are aware of this, unfortunately maintenance could not be assured for a long period. We are currently adding some documentation and will be performing validation soon, looking to tag release 3.6.0 in a matter of weeks.

https://github.com/shibatch/sleef/discussions/498

Best,

**Comment by blapie** [comment]
New release tag created. I messaged the person usually in charge of packaging for distributions, but please spread the word.

**Comment by xypron** [comment]
Thank you @blapie. Debian experimental has already picked up the new release.
