### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by musm** [shibatch/sleef#51]
Dear @shibatch.  I am offering the following logo from my julia port, if you would like to use it instead:
https://github.com/musm/SLEEF.jl
https://github.com/musm/SLEEF.jl/blob/master/doc/src/assets/logo.svg
Of course there is no obligation on this. Just thought I would throw it out there.

**Comment by shibatch** [comment]
Thank you for proposing a new logo.
I will include it in the packages of future versions of SLEEF, though I will use the current logo as the main logo.

A sleef means a soup ladle in dutch, so I drew a soup ladle.
http://dictionary.sensagent.com/sleef/nl-en/

I would consider changing the main logo if you include a picture of soup ladle in the logo image.

**Comment by musm** [comment]
Hi @shibatch , I was not aware of the underlying meaning of sleef in dutch. In this case I think the current logo is more appropriate than the one proposed and suggested. Thanks for the consideration.
