### ISSUE TITLE
Missing unversioned symbolic link for GNUABI version in 3.6

### ISSUE THREAD

**Issue by musicinmybrain** [shibatch/sleef#532]
In release 3.6, with `-DSLEEF_BUILD_GNUABI_LIBS:BOOL=TRUE`, CMake no longer produces the unversioned shared-library symlink `libsleefgnuabi.so`.

Only the library `libsleefgnuabi.so.3.6` and the symbolic link `libsleefgnuabi.so.3` are installed.

(See https://sleef.org/additional.xhtml#gnuabi for an example using `-lsleefgnuabi`: this requires `libsleefgnuabi.so`.)

Both `libsleef.so` and `libsleefquad.so` have the correct unversioned symbolic links.

**Comment by musicinmybrain** [comment]
It looks like 29391ccd9d513132fc802a198f8b801fb273cb59 might affect this, but I haven’t tested it yet.

**Comment by blapie** [comment]
Thanks for the report. Will look into that as soon as I can.

> It looks like https://github.com/shibatch/sleef/commit/29391ccd9d513132fc802a198f8b801fb273cb59 might affect this, but I haven’t tested it yet.

You are right, it very well could solve that. But not 100% sure, haven't checked more closely yet.

**Comment by musicinmybrain** [comment]
> It looks like [29391cc](https://github.com/shibatch/sleef/commit/29391ccd9d513132fc802a198f8b801fb273cb59) might affect this, but I haven’t tested it yet.

It affects it, but the wrong way: now `libsleef.so` is also missing the unversioned symlink!

Note that `libsleef.so`/`libsleefgnuabi.so` *are* in the CMake build directory, but they are not *installed* anymore.
