### ISSUE TITLE
Build iutadvsimd with the same source files as iut*

### ISSUE THREAD

**Issue by diaena** [shibatch/sleef#56]
We currently need a special case for building the ADVSIMD test executable. This is something that needs fixing.

**Comment by shibatch** [comment]
I think you don't need to modify the C source code.

**Comment by diaena** [comment]
What I know is that the compilation fails without the single and double precision source files for simd code. I didn't look very closely into it, but followed what the current build system does and did the same with cmake.

**Comment by shibatch** [comment]
I modified the corresponding part of the original makefile as follows, and it compiles.

```
iutadvsimd : ../../lib/libsleef.$(DLLSUFFIX) ../../include/sleef.h iutsimdmain.o iutsimd.c testerutil.c ../libm/renameadvsimd.h ../../include/sleef.h
        $(CC) $(CFLAGS) -DENABLE_ADVSIMD $(ADVSIMDFLAG) iutsimdmain.o iutsimd.c testerutil.c -o iutadvsimd -lsleef -lm $(LIB)

../libm/renameadvsimd.h :
        +"$(MAKE)" --directory=../libm renameadvsimd.h
```

I will check your CMakeLists.txt tomorrow.

**Comment by shibatch** [comment]
You have to modify iutsimd.c in the following way.

```
#ifdef ENABLE_ADVSIMD
#define CONFIG 1
#include "helperadvsimd.h"
#include "renameadvsimd.h"
typedef Sleef_float64x2_t_2 vdouble2;
typedef Sleef_float32x4_t_2 vfloat2;
#endif
```

**Comment by diaena** [comment]
I will submit a pull request with this change once the refactoring one gets merged in as I've based all my changed on the refactored code.

**Comment by fpetrogalli-arm** [comment]
Merged in https://github.com/shibatch/sleef/pull/58
