### ISSUE TITLE
About a bug in gcc-13

### ISSUE THREAD

**Issue by shibatch** [shibatch/sleef#594]
**Describe the bug**

This issue is about a bug in gcc-13 that was already addressed in https://github.com/shibatch/sleef/pull/592.

When compiling with gcc-13, the sign of signed zero sometimes seems to be wrong. The exact condition of occurrence is unknown.

**Environment**

When a PUREC* helper is used, this problem occurs on every architecture.
In addition to this, VXE helpers are also affected by this bug.

**Comment by blapie** [comment]
Thank you for reporting! We will take the time to look into it. This type of errors rings a bell, if it was fixed it might not require a more recent version of gcc13.

**Comment by blapie** [comment]
I'm going to close that ticket, since [recent CI runs](https://github.com/shibatch/sleef/actions/runs/11559254259/job/32173728766) show that a recent enough gcc-13 has the required fix and allow all tests to pass.
