### ISSUE TITLE
Updates to cmake-transition branch

### ISSUE THREAD

**Issue by xoofx** [shibatch/sleef#67]
Hi, 
So I have started to pull the `cmake-transition` branch.
I have already open the PR #66 to fix gnuabi problem.

I will submit other patches, mainly to simplify the process of mkrename/headers, which is currently not robust (don't fail if the file is not generated), a bit hacky (using external cmake command), and cumbersome to follow (external cmake files, not configurable...etc.)

I have already refactored the `mkrename` part and it seems to work well. I will do the same for the header files.

Let me know if I can proceed further.
Thanks!

**Comment by shibatch** [comment]
As I said, this branch have been mainly developed by @diaena. I think we first need to talk to her about this.

@fpetrogalli-arm : Do you have a working e-mail address of hers?

**Comment by xoofx** [comment]
I don't mind continue the work of @diaena if this is fine, as we have a need for this and it would benefits others as well (otherwise I will keep my branch separated for the time being)

**Comment by fpetrogalli-arm** [comment]
@xoofx , I think we can safely close this issue?

**Comment by xoofx** [comment]
Yes, sorry, thanks
