### ISSUE TITLE
Argument reduction for trigonometric funtions in case of huge arguments

### ISSUE THREAD

**Issue by carlkl** [shibatch/sleef#7]
IMHO it would make sense to add logic for additional argument reduction (i.e. payne-hanek) for huge arguments at least for the non-vectoriced pure-c variant of sleef. 

As this is table based this is obviously not possible for the vectorized SIMD variants.

**Comment by shibatch** [comment]
Could you explain in what situation argument reduction for such huge arguments is needed?
I think you are the 4th person who asked me to implement that feature, but no one has explained that point.

**Comment by carlkl** [comment]
See i.e.  Derek O'Conners quote on the Python bug tracker https://bugs.python.org/issue8309

> I quote from Ng's paper :
http://www.derekroconnor.net/Software/Ng--ArgReduction.pdf

> It is often argued that being concerned about large arguments is unnecessary, because sophisticated users simply know better than to compute with large angles. It is our contention that this position is suboptimal, because:

> 1. It places an unnecessary burden on the user.
> 2. The consequences of producing incorrect (inaccurate)answers may be catastrophic; many people assume that computers can do arithmetic very well. While numerical analysts know better, not all programmers are numerical analysts, nor should they be.
> 3. It is a vendors responsibility to provide answers that are as correct as possible.

> Derek O'Connor

I think the non-vectorized trig functions should be as exact as possible even for huge arguments mostly because of the 2nd argument.

**Comment by shibatch** [comment]
If the argument is very large, obviously ULP of that argument becomes large.
So, the result of computation of trig functions become inaccurate anyway.
The assumption that computers always do arithmetic very well is just wrong.
This burden exists since when the user decides to use FP numbers of limited accuracy.

**Comment by carlkl** [comment]
At least the reduced range for trig functions should also be mentioned in the README.

BTW: A accuracy problem for trigs was found in the FPU hardware, see [Intel overstates FPU accuracy](http://notabs.org/fpuaccuracy) even for small sized arguments near PI. Numerical deviations in such cases can be avoided with using sleef AFAIK. This could be mentioned as well.

**Comment by shibatch** [comment]
Please see doc/SPECIFICATION.
SLEEF is accurate for small sized arguments near (n PI).

**Comment by carlkl** [comment]
Thanks

**Comment by shibatch** [comment]
You're welcome.
Please don't hesitate to ask me if you have other questions.
