### ISSUE TITLE
Building IUT with MSVC

### ISSUE THREAD

**Issue by shibatch** [shibatch/sleef#71]
It is now time to think how we can build testing programs with MSVC.
The main obstacle is building libmpfr.

The easy way is to build the IUT with Cygwin, as it is done with the old makefile.

Another way is to use the version that can be built with MSVC.
https://github.com/BrianGladman/mpfr

**Comment by xoofx** [comment]
If we could make it working with MSVC mpfr branch, that would simplify the setup (and avoid installing cygwin).
I can have a look later if you want, as I'm mostly working on Windows.

**Comment by shibatch** [comment]
Thanks. Please check if it is easy.
