### ISSUE TITLE
[libm] Remove dependency on libm

### ISSUE THREAD

**Issue by shibatch** [shibatch/sleef#79]
In order to allow using sleef as a substitute of libm, it is desirable to remove dependency on libm.

As we already discussed in https://github.com/shibatch/sleef/issues/30 and https://github.com/shibatch/sleef/issues/33, we can consider a use case where users link their programs against libsleef instead of libm. In this case, all standard math functions are implemented by libsleef. libsleef should export all symbols exported by libm.

In order to realize this, we need to remove all dependency on libm from sleef. For this, calls for libm functions have to be all replaced with builtin functions, e.g. sqrt is replaced by _builtin_sqrt. Since the names of the builtin functions are compiler-dependent, we need some renaming and detection.

We can think of both merits and demerits in doing this.

Merits :
* It is relatively easy to make the compiler call the vectorized math functions after automatic vectorization.
* As a result, users can easily use the vectorized math functions without modifying the source code.

Demerits :
* Users cannot call the functions in the original libm.
* This feature might not be supported on some combinations of OS and compiler.

Although there is some demerit, sleef should support usage like this. Currently, the gnuabi version and the normal version of sleef are built. It is natural to add scalar math.h functions to the gnuabi version.

There is also a requirement of making the scalar functions return the exactly same values as the vectorized functions, as discussed in https://github.com/shibatch/sleef/issues/47 . This can be realized by calling dispatcher functions from the API of the gnuabi sleef.

**Comment by carlkl** [comment]
I want to referenc it to https://github.com/shibatch/sleef/issues/20 as well. As far I can see only sqrt and sqtf are affected. If the internal usage of these functions are used in a way, that no NaN or INFs could be expected `sqrtss` and `sqrtsd` assembler could be used, at least on x86 architdectures.
