### ISSUE TITLE
Running tests on Intel sde

### ISSUE THREAD

**Issue by shibatch** [shibatch/sleef#85]
I am considering to run the tests on Intel software development emulator. With this, we can test AVX2 and AVX512F implementations in addition to the currently tested ones.

Testing won’t be too much slower than now, since only IUT runs on the emulator.

We can see a similar travis configuration in the following pull request.

https://github.com/flame/blis/pull/124

**Comment by shibatch** [comment]
I checked the license of sde, and I found that redistribution is not allowed. The package cannot be downloaded directly from Intel's server since we need to agree the license. So, we need to put the package at somewhere else, and download the package to the CI server. I am not fully sure if this does not infringe the license.

**Comment by jeffhammond** [comment]
I downloaded the install file and put it in Dropbox with the location hidden by Travis secure environment variables. 

When I talked to SDE team about this, they were trying to enforce license acceptance on users. You’ll accept license when you download so I don’t think it’s a problem as long as you’re the only person running the SDE binary you download. However, I can ask if you think it’s necessary.

**Comment by shibatch** [comment]
Hi Jeff,
Since everything is visible publicly, I don't want to do anything suspicious. I guess there is demand by people other than us. Hiding a download location by a secure environment variable is a nice idea, and it sounds not infringing the license. I think it would be easier for people if usage on CI environments is clearly stated in the license.

@fpetrogalli-arm How do you think? If it is okay for you, I will start implementing it.

**Comment by jeffhammond** [comment]
I will see what I can do to address this.

**Comment by shibatch** [comment]
Thank you so much. Please also tell them to allow using Intel Compiler on CIs. 🙂

**Comment by jeffhammond** [comment]
Write me an email (GitHub shows it) and we can discuss. That’s a problem I
know how to solve.
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by fpetrogalli-arm** [comment]
@shibatch : of course it is OK for me, and I am looking forward to see it execute on CI!
@jeffhammond : thanks for reaching out!
