### ISSUE TITLE
Algorithm documentation

### ISSUE THREAD

**Issue by musm** [shibatch/sleef#86]
Is there any chance we could get documentation on the algorithms used for each function, e.g. details on the reduction, approximation, scaling back  methods?  I know this is asking much, but it would help a lot.

**Comment by shibatch** [comment]
I am planning to write a new paper on it. I will give you a preprint when it’s done.

**Comment by musm** [comment]
Thank you, looking forward to it!!

**Comment by carlkl** [comment]
@shibatch , I guess these slides are still valid? 
https://de.slideshare.net/NaokiShibata/efficient-evaluation-methods-of-elementary-functions-suitable-for-simd-computation

**Comment by shibatch** [comment]
That one is very old. New versions use different techniques.

**Comment by carlkl** [comment]
Good to know, I'm looking forward to the new paper as well.

**Comment by shibatch** [comment]
@musm For the polynomial approximation, it is basically same as Remez's algorithm.
There is explanation in page 41 of the text book "Elementary Functions Algorithms and Implementation".

https://doc.lagout.org/science/0_Computer%20Science/2_Algorithms/Elementary%20Functions_%20Algorithms%20and%20Implementation%20%282nd%20ed.%29%20%5BMuller%202005-10-24%5D.pdf

In the newer revision of this text book, description for minimizing relative error is also added.

Could you tell me what you want to know beyond this regarding to the approximation, if any.

**Comment by oloeopia** [comment]
Any news on the preprint?

**Comment by shibatch** [comment]
@oloeopia Send me an email and I will send you the PDF.

**Comment by oloeopia** [comment]
@shibatch Sent.

**Comment by zhuohoudeputao** [comment]
> @oloeopia Send me an email and I will send you the PDF.

Could you please also send me the preprint? Or have you published it? Thank you.

**Comment by shibatch** [comment]
Here you are.

https://ieeexplore.ieee.org/document/8936472
